# Generated by Django 4.1.7 on 2023-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('published_date', models.DateField()),
            ],
        ),
    ]
